Update Jenkinsfile

diff --git a/Calculator App/Jenkinsfile b/Calculator App/Jenkinsfile
--- a/Calculator App/Jenkinsfile
+++ b/Calculator App/Jenkinsfile
@@ -6,7 +6,7 @@ pipeline {
         REGISTRY_USER = 'gowshikm'                  // DockerHub username
         DOCKER_CREDS  = credentials('gowshikm')     // Jenkins credentials ID
         DOCKER_TAG    = "${BUILD_ID}"               // Jenkins build ID
-        IMAGE_NAME    = "${env.REGISTRY_USER}/${env.REPO_NAME}"
+       
     }
 
     stages {
@@ -20,7 +20,9 @@ pipeline {
         stage('Build Docker Image') {
             steps {
                 script {
-                    docker.build("${env.IMAGE_NAME}:${env.DOCKER_TAG}")
+                    def imageName = "${env.REGISTRY_USER}/${env.REPO_NAME}"
+                    docker.build("${imageName}:${env.DOCKER_TAG}")
+
                 }
             }
         }
@@ -48,19 +50,19 @@ pipeline {
     }
 
     post {
-        // always {
-        //     echo 'Docker build pipeline finished.'
-        //     script {
-        //         try {
-        //            node{ 
-        //             sh "docker rmi ${env.IMAGE_NAME}:${env.DOCKER_TAG} || true"
-        //             sh "docker rmi ${env.IMAGE_NAME}:latest || true" 
-        //            }
-        //         } catch (Exception e) {
-        //             echo "Cleanup failed: ${e.message}"
-        //         }
-        //     }
-        // }
+        always {
+            echo 'Docker build pipeline finished.'
+            script {
+                try {
+                   node{ 
+                    sh "docker rmi ${env.IMAGE_NAME}:${env.DOCKER_TAG} || true"
+                    sh "docker rmi ${env.IMAGE_NAME}:latest || true" 
+                   }
+                } catch (Exception e) {
+                    echo "Cleanup failed: ${e.message}"
+                }
+            }
+        }
         success {
             echo "Image pushed successfully: ${env.IMAGE_NAME}:latest"
         }
