Update Jenkinsfile

diff --git a/Calculator App/Jenkinsfile b/Calculator App/Jenkinsfile
--- a/Calculator App/Jenkinsfile
+++ b/Calculator App/Jenkinsfile
@@ -48,19 +48,19 @@ pipeline {
     }
 
     post {
-        always {
-            echo 'Docker build pipeline finished.'
-            script {
-                try {
-                   node{ 
-                    sh "docker rmi ${env.IMAGE_NAME}:${env.DOCKER_TAG} || true"
-                    sh "docker rmi ${env.IMAGE_NAME}:latest || true" 
-                   }
-                } catch (Exception e) {
-                    echo "Cleanup failed: ${e.message}"
-                }
-            }
-        }
+        // always {
+        //     echo 'Docker build pipeline finished.'
+        //     script {
+        //         try {
+        //            node{ 
+        //             sh "docker rmi ${env.IMAGE_NAME}:${env.DOCKER_TAG} || true"
+        //             sh "docker rmi ${env.IMAGE_NAME}:latest || true" 
+        //            }
+        //         } catch (Exception e) {
+        //             echo "Cleanup failed: ${e.message}"
+        //         }
+        //     }
+        // }
         success {
             echo "Image pushed successfully: ${env.IMAGE_NAME}:latest"
         }
